@import Foundation;

typedef enum : uint8_t {
    kRevDrive_Continuous = 0x78,
    kRevTurnLeftByTime = 0x73,
    kRevTurnRightByTime = 0x74,
    kRevDriveForwardByTime = 0x71,
    kRevBatteryLevel = 0x79,
    kRevPlaySound = 0x06,
    kRevSetTrackingMode = 0x91,
    kRevSetTrackingSensorOnOff = 0x92,
    kRevTrackingSensorStatus = 0x93,
    kRevTrackingSettings = 0x94,
    kRevSendIRCommand = 0x95,
    kRevSetTraction = 0x96,
    kRevStop = 0x77,
    kRevGetLEDColor = 0x83,
    kRevSetLEDColor = 0x84,
    kRevFlashLEDColor = 0x89,
    kRevPulsateLEDColor = 0x90,
    kRevGetHardwareVersion = 0x19,
    kRevSetBumpNotifyOnOff = 0x97,
    kRevBumpNotify = 0x98,
    kRevGetSoftwareVersion = 0x14,
    kRevSetSoundVolume = 0x15,
    kRevGetSoundVolume = 0x16,
    kRevRampUpdateNotify = 0xa2,
    kRevBeaconStatusUpdate = 0x99,
    kRevGetMotorVoltage = 0xa3,
    kRevSetSkyTXPower = 0x9a,       // For REV2 cars only
    kRevGetSkyTXPower = 0x9b,       // For REV2 cars only
    kRevSetCalibrationData = 0x9c,  // For REV2 cars only
    kRevGetCalibrationData = 0x9d,  // For REV2 cars only
    
    // For connected broadcast usage
    kRevConnectedBroadcast = 0x28,
} kRevCommand;

typedef enum : uint8_t {
    kRev2TXFrontGun         = (1 << 0), // => 00000001
    kRev2TXGroundBeacon     = (1 << 1), // => 00000010
    kRev2TXSkyFront         = (1 << 2),  // => 00000100
    kRev2TXSkyMiddle        = (1 << 3),  // => 00001000
    kRev2TXSkyBack          = (1 << 4),  // => 00010000
    kRev2TXSkySide          = (1 << 5)  // => 00100000
} kRev2TXDirection;

typedef enum : uint8_t {
    kRevDriveCont_FW_Speed1 = 0x00, // Forward slowest
    kRevDriveCont_FW_Speed2,
    kRevDriveCont_FW_Speed3,
    kRevDriveCont_FW_Speed4,
    kRevDriveCont_FW_Speed5,
    kRevDriveCont_FW_Speed6,
    kRevDriveCont_FW_Speed7,
    kRevDriveCont_FW_Speed8,
    kRevDriveCont_FW_Speed9,
    kRevDriveCont_FW_Speed10,
    kRevDriveCont_FW_Speed11,
    kRevDriveCont_FW_Speed12,
    kRevDriveCont_FW_Speed13,
    kRevDriveCont_FW_Speed14,
    kRevDriveCont_FW_Speed15,
    kRevDriveCont_FW_Speed16,
    kRevDriveCont_FW_Speed17,
    kRevDriveCont_FW_Speed18,
    kRevDriveCont_FW_Speed19,
    kRevDriveCont_FW_Speed20,
    kRevDriveCont_FW_Speed21,
    kRevDriveCont_FW_Speed22,
    kRevDriveCont_FW_Speed23,
    kRevDriveCont_FW_Speed24,
    kRevDriveCont_FW_Speed25,
    kRevDriveCont_FW_Speed26,
    kRevDriveCont_FW_Speed27,
    kRevDriveCont_FW_Speed28,
    kRevDriveCont_FW_Speed29,
    kRevDriveCont_FW_Speed30,
    kRevDriveCont_FW_Speed31,
    kRevDriveCont_FW_Speed32, // Forward fastest
    
    kRevDriveCont_BW_Speed1 = 0x20, // Backward slowest
    kRevDriveCont_BW_Speed2,
    kRevDriveCont_BW_Speed3,
    kRevDriveCont_BW_Speed4,
    kRevDriveCont_BW_Speed5,
    kRevDriveCont_BW_Speed6,
    kRevDriveCont_BW_Speed7,
    kRevDriveCont_BW_Speed8,
    kRevDriveCont_BW_Speed9,
    kRevDriveCont_BW_Speed10,
    kRevDriveCont_BW_Speed11,
    kRevDriveCont_BW_Speed12,
    kRevDriveCont_BW_Speed13,
    kRevDriveCont_BW_Speed14,
    kRevDriveCont_BW_Speed15,
    kRevDriveCont_BW_Speed16,
    kRevDriveCont_BW_Speed17,
    kRevDriveCont_BW_Speed18,
    kRevDriveCont_BW_Speed19,
    kRevDriveCont_BW_Speed20,
    kRevDriveCont_BW_Speed21,
    kRevDriveCont_BW_Speed22,
    kRevDriveCont_BW_Speed23,
    kRevDriveCont_BW_Speed24,
    kRevDriveCont_BW_Speed25,
    kRevDriveCont_BW_Speed26,
    kRevDriveCont_BW_Speed27,
    kRevDriveCont_BW_Speed28,
    kRevDriveCont_BW_Speed29,
    kRevDriveCont_BW_Speed30,
    kRevDriveCont_BW_Speed31,
    kRevDriveCont_BW_Speed32, // Backward fastest
    
    kRevDriveCont_Left_Speed1 = 0x60, // Turn left slowest
    kRevDriveCont_Left_Speed2,
    kRevDriveCont_Left_Speed3,
    kRevDriveCont_Left_Speed4,
    kRevDriveCont_Left_Speed5,
    kRevDriveCont_Left_Speed6,
    kRevDriveCont_Left_Speed7,
    kRevDriveCont_Left_Speed8,
    kRevDriveCont_Left_Speed9,
    kRevDriveCont_Left_Speed10,
    kRevDriveCont_Left_Speed11,
    kRevDriveCont_Left_Speed12,
    kRevDriveCont_Left_Speed13,
    kRevDriveCont_Left_Speed14,
    kRevDriveCont_Left_Speed15,
    kRevDriveCont_Left_Speed16,
    kRevDriveCont_Left_Speed17,
    kRevDriveCont_Left_Speed18,
    kRevDriveCont_Left_Speed19,
    kRevDriveCont_Left_Speed20,
    kRevDriveCont_Left_Speed21,
    kRevDriveCont_Left_Speed22,
    kRevDriveCont_Left_Speed23,
    kRevDriveCont_Left_Speed24,
    kRevDriveCont_Left_Speed25,
    kRevDriveCont_Left_Speed26,
    kRevDriveCont_Left_Speed27,
    kRevDriveCont_Left_Speed28,
    kRevDriveCont_Left_Speed29,
    kRevDriveCont_Left_Speed30,
    kRevDriveCont_Left_Speed31,
    kRevDriveCont_Left_Speed32, // Turn left fastest
    /*
     OR right spin:0xE1(slow)~0xFF(fast)
     OR Left spin:0xC1(slow)~0xE0(fast
     */
    kRevDriveCont_Right_Speed1 = 0x40, // Turn right slowest
    kRevDriveCont_Right_Speed2,
    kRevDriveCont_Right_Speed3,
    kRevDriveCont_Right_Speed4,
    kRevDriveCont_Right_Speed5,
    kRevDriveCont_Right_Speed6,
    kRevDriveCont_Right_Speed7,
    kRevDriveCont_Right_Speed8,
    kRevDriveCont_Right_Speed9,
    kRevDriveCont_Right_Speed10,
    kRevDriveCont_Right_Speed11,
    kRevDriveCont_Right_Speed12,
    kRevDriveCont_Right_Speed13,
    kRevDriveCont_Right_Speed14,
    kRevDriveCont_Right_Speed15,
    kRevDriveCont_Right_Speed16,
    kRevDriveCont_Right_Speed17,
    kRevDriveCont_Right_Speed18,
    kRevDriveCont_Right_Speed19,
    kRevDriveCont_Right_Speed20,
    kRevDriveCont_Right_Speed21,
    kRevDriveCont_Right_Speed22,
    kRevDriveCont_Right_Speed23,
    kRevDriveCont_Right_Speed24,
    kRevDriveCont_Right_Speed25,
    kRevDriveCont_Right_Speed26,
    kRevDriveCont_Right_Speed27,
    kRevDriveCont_Right_Speed28,
    kRevDriveCont_Right_Speed29,
    kRevDriveCont_Right_Speed30,
    kRevDriveCont_Right_Speed31,
    kRevDriveCont_Right_Speed32, // Turn right fastest
    
} kRevDriveContinuousValue;

typedef NS_OPTIONS(uint8_t, kRevSoundFileValue) {
    kRevSoundFile_A3400_34K_ONEKHZ_500MS_8K16BIT_A34            = (1+0),
    kRevSoundFile_A3400_34K_SHORT_MUTE_FOR_STOP_A34             = (1+1),
    kRevSoundFile_REV_ATTACK_GUN_1_FIRE_A34                     = (1+2),
    kRevSoundFile_REV_ATTACK_GUN_2_FIRE_A34                     = (1+3),
    kRevSoundFile_REV_ATTACK_GUN_3_FIRE_A34                     = (1+4),
    kRevSoundFile_REV_ATTACK_GUN_4_FIRE_A34                     = (1+5),
    kRevSoundFile_REV_ATTACK_GUN_5_FIRE_A34                     = (1+6),
    kRevSoundFile_REV_ATTACK_GUN_6_FIRE_A34                     = (1+7),
    kRevSoundFile_REV_ATTACK_SPECIAL_AIRSTRIKE_CHARGE_A34       = (1+8),
    kRevSoundFile_REV_ATTACK_SPECIAL_AIRSTRIKE_FIRE_A34         = (1+9),
    kRevSoundFile_REV_ATTACK_SPECIAL_BURSTSHOT_CHARGE_A34       = (1+10),
    kRevSoundFile_REV_ATTACK_SPECIAL_BURSTSHOT_FIRE_A34         = (1+11),
    kRevSoundFile_REV_ATTACK_SPECIAL_CANNON_CHARGE_A34          = (1+12),
    kRevSoundFile_REV_ATTACK_SPECIAL_CANNON_FIRE_A34            = (1+13),
    kRevSoundFile_REV_ATTACK_SPECIAL_EMP_CHARGE_A34             = (1+14),
    kRevSoundFile_REV_ATTACK_SPECIAL_EMP_FIRE_A34               = (1+15),
    kRevSoundFile_REV_ATTACK_SPECIAL_GRENADELAUNCHER_CHARGE_A34 = (1+16),
    kRevSoundFile_REV_ATTACK_SPECIAL_GRENADELAUNCHER_FIRE_A34   = (1+17),
    kRevSoundFile_REV_ATTACK_SPECIAL_MISSILE_CHARGE_A34         = (1+18),
    kRevSoundFile_REV_ATTACK_SPECIAL_MISSILE_FIRE_A34           = (1+19),
    kRevSoundFile_REV_ATTACK_SPECIAL_SHOCKWAVE_CHARGE_A34       = (1+20),
    kRevSoundFile_REV_ATTACK_SPECIAL_SHOCKWAVE_FIRE_A34         = (1+21),
    kRevSoundFile_REV_ATTACK_SPECIAL_TRACTORBEAM_CHARGE_A34     = (1+22),
    kRevSoundFile_REV_ATTACK_SPECIAL_TRACTORBEAM_FIRE_A34       = (1+23),
    kRevSoundFile_REV_BOOSTER_BERSERKER_ON_A34                  = (1+24),
    kRevSoundFile_REV_BOOSTER_BERSERKER_LOOP_A34                = (1+25),
    kRevSoundFile_REV_BOOSTER_HEALTHRECHARGE_A34                = (1+26),
    kRevSoundFile_REV_BOOSTER_INVERTDRIVE_A34                   = (1+27),
    kRevSoundFile_REV_BOOSTER_SHIELD_ACTIVATE_A34               = (1+28),
    kRevSoundFile_REV_BOOSTER_SHIELD_DEACTIVATE_A34             = (1+29),
    kRevSoundFile_REV_BOOSTER_SHIELD_ON_A34                     = (1+30),
    kRevSoundFile_REV_BOOSTER_SLUG_A34                          = (1+31),
    kRevSoundFile_REV_BOOSTER_TURBO_A34                         = (1+32),
    kRevSoundFile_REV_CAR_ALERTED_A34                           = (1+33),
    kRevSoundFile_REV_CAR_ALERTED_RAMP_A34                      = (1+34),
    kRevSoundFile_REV_CAR_CONFIRM_1_A34                         = (1+35),
    kRevSoundFile_REV_CAR_CONFIRM_2_A34                         = (1+36),
    kRevSoundFile_REV_CAR_CONFIRM_3_A34                         = (1+37),
    kRevSoundFile_REV_CAR_CONNECT_A34                           = (1+38),
    kRevSoundFile_REV_CAR_DISCONNECT_A34                        = (1+39),
    kRevSoundFile_REV_CAR_HORN_1_A34                            = (1+40),
    kRevSoundFile_REV_CAR_LOWBATTERY_A34                        = (1+41),
    kRevSoundFile_REV_CAR_PARKED_A34                            = (1+42),
    kRevSoundFile_REV_CAR_REVIVE_A34                            = (1+43),
    kRevSoundFile_REV_CAR_SIREN_1_A34                           = (1+44),
    kRevSoundFile_REV_CAR_TYRESCREECH_1_A34                     = (1+45),
    kRevSoundFile_REV_CAR_TYRESCREECH_2_A34                     = (1+46),
    kRevSoundFile_REV_CAR_TYRESCREECH_3_A34                     = (1+47),
    kRevSoundFile_REV_CAR_WARNING_A34                           = (1+48),
    kRevSoundFile_REV_DAMAGE_EXPLOSION_1_A34                    = (1+49),
    kRevSoundFile_REV_DAMAGE_EXPLOSION_2_A34                    = (1+50),
    kRevSoundFile_REV_DAMAGE_EXPLOSION_3_A34                    = (1+51),
    kRevSoundFile_REV_DAMAGE_EXPLOSION_4_A34                    = (1+52),
    kRevSoundFile_REV_DAMAGE_GLASS_1_A34                        = (1+53),
    kRevSoundFile_REV_DAMAGE_GLASS_2_A34                        = (1+54),
    kRevSoundFile_REV_DAMAGE_MALFUNCTION_1_A34                  = (1+55),
    kRevSoundFile_REV_DAMAGE_MALFUNCTION_2_A34                  = (1+56),
    kRevSoundFile_REV_DAMAGE_METAL_1_A34                        = (1+57),
    kRevSoundFile_REV_DAMAGE_METAL_2_A34                        = (1+58),
    kRevSoundFile_REV_DAMAGE_RICOCHET_1_A34                     = (1+59),
    kRevSoundFile_REV_DAMAGE_RICOCHET_2_A34                     = (1+60),
    kRevSoundFile_REV_DAMAGE_SHIELDSHATTER_A34                  = (1+61),
    kRevSoundFile_REV_DAMAGE_SPECIAL_AIRSTRIKE_IMPACT_1_A34     = (1+62),
    kRevSoundFile_REV_DAMAGE_SPECIAL_AIRSTRIKE_IMPACT_2_A34     = (1+63),
    kRevSoundFile_REV_DAMAGE_SPECIAL_CANNON_IMPACT_A34          = (1+64),
    kRevSoundFile_REV_DAMAGE_SPECIAL_EMP_IMPACT_A34             = (1+65),
    kRevSoundFile_REV_DAMAGE_SPECIAL_GRENADELAUNCHER_IMPACT_A34 = (1+66),
    kRevSoundFile_REV_DAMAGE_SPECIAL_MISSILE_IMPACT_A34         = (1+67),
    kRevSoundFile_REV_DAMAGE_SPECIAL_SHOCKWAVE_IMPACT_A34       = (1+68),
    kRevSoundFile_REV_DAMAGE_SPECIAL_TRACTORBEAM_IMPACT_A34     = (1+69),
    kRevSoundFile_REV_DAMAGE_DEATH_1_A34                        = (1+70),
    kRevSoundFile_REV_DAMAGE_DEATH_2_A34                        = (1+71),
    kRevSoundFile_REV_DAMAGE_DEATH_3_A34                        = (1+72),
};

@interface REVCommandValues : NSObject

@end

